<a href="https://colab.research.google.com/github/esdrasantos/statistical-concepts-and-practice/blob/main/csfm_mod_10_kruskal_wallis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Kruskal-Wallis (3+ Médias - Medianas)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

In [4]:
notas = pd.read_excel('/content/drive/MyDrive/Curso de Estatística 2.0/Arquivos Excel/Dados3_CursoEstatistica.xlsx', sheet_name=6)

notas.head()

    Etnia  Nota
0  blacks  1246
1  blacks  1148
2  blacks  1300
3  blacks  1404
4  blacks  1396

In [5]:
notas_g = notas.groupby('Etnia')['Nota'].apply(list)

notas_g.head()

Etnia
asians                  [1623, 1550, 1936, 1800, 1750]
blacks            [1246, 1148, 1300, 1404, 1396, 1450]
hispanics               [1267, 1228, 1450, 1351, 1280]
whites       [1581, 1649, 981, 1877, 1629, 1800, 1423]
Name: Nota, dtype: object

In [6]:
from scipy.stats import kruskal

stat, p = kruskal(*notas_g)

print('stat=%.4f, p=%.4f' % (stat, p))

stat=11.4761, p=0.0094

In [8]:
# Decisão:

alpha = 0.05

if p > alpha:
  print('Não rejeitamos a hipótese nula')
  print('Logo, as medianas são iguais')
else:
  print('Rejeitamos a hipótese nula')
  print('Logo, existe ao menos uma mediana diferente')

Rejeitamos a hipótese nula
Logo, existe ao menos uma mediana diferente

In [ ]:
!pip install scikit-posthocs

In [10]:
# POST-HOC
# Teste de Dunn (Comparações multiplas)

import scikit_posthocs as sp

sp.posthoc_dunn(notas, val_col='Nota', group_col='Etnia', p_adjust='bonferroni')

             asians    blacks  hispanics    whites
asians     1.000000  0.041598   0.040909  1.000000
blacks     0.041598  1.000000   1.000000  0.278379
hispanics  0.040909  1.000000   1.000000  0.258665
whites     1.000000  0.278379   0.258665  1.000000