<a href="https://colab.research.google.com/github/esdrasantos/statistical-concepts-and-practice/blob/main/cstfm_mod_10_teste_do_sinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Teste do Sinal

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
import pandas as pd
import numpy as np

In [8]:
dominos = pd.read_excel('/content/drive/MyDrive/Curso de Estatística 2.0/Arquivos Excel/Dados3_CursoEstatistica.xlsx', sheet_name=7)

dominos.head()

   Cliente  Antiga  Nova
0        1       3     4
1        2       3     2
2        3       2     5
3        4       4     4
4        5       2     5

In [25]:
import statsmodels.api as sm

dominos['Diff'] = dominos['Antiga'] - dominos['Nova']

dominos.head()

   Cliente  Antiga  Nova  Diff
0        1       3     4    -1
1        2       3     2     1
2        3       2     5    -3
3        4       4     4     0
4        5       2     5    -3

In [26]:
# Contar os sinais +

positivos = dominos[dominos['Diff'] > 0].sum()
positivos

Cliente    42
Antiga     15
Nova        9
Diff        6
dtype: int64

In [27]:
# Numero de observações validas (não nulas)

n = len(dominos[dominos['Diff'] != 0])
n

18

In [43]:
# Teste binomial
# Utilizado quando se tem duas opções de valor: sucesso e insucesso (+ ou -)

p = 0.5 # Probabilidade de sucesso (+)

pvalor = sm.stats.binom_test(len(positivos), n, p, alternative='smaller')

pvalor

np.float64(0.01544189453125)

In [48]:
# Decisão
alfa = 0.05

if pvalor < alfa:
  print('Rejeitar H0')
  print('Portanto, as proporções dos sinais são estatisticamente diferentes')
  print('Nesse caso, em específico, o a proporção de Antiga e menor que a proporção de Nova')

else:
  print('Aceitar H0')
  print('Portanto, as proporções dos sinais são estatisticamente iguais')
  print('Nesse caso, em específico, o a proporção de Antiga e maior ou igual que a proporção de Nova')

Rejeitar H0
Portanto, as proporções dos sinais são estatisticamente diferentes
Nesse caso, em específico, o a proporção de Antiga e menor que a proporção de Nova